### ISSUE TITLE
Notification sent to timed out

### ISSUE THREAD

**Issue by Xenomes** [dnpwwo/Domoticz-Google-Plugin#5]
Hi,

My Pi system is running Domoticz 4.10570 and the latest Google plugin of 20-3-2019
I am unable to send a notification to my Google Home Mini. The mp3 file is created and external it is playable, but not sent to the google home I get this error message.
`Error: (Google Home) Notification 'Test knop', sent to 'Google Huiskamer' timed out`
I don't know what to do get it working.

My setting are
![afbeelding](https://user-images.githubusercontent.com/11648297/54951360-b46dab00-4f43-11e9-92a0-2919cdd08faf.png)

Here is a part of the log:
>  2019-03-25 21:29:52.581 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-03-25 21:29:52.624 (Google Home) Processing 'onHeartbeatCallback' message
2019-03-25 21:29:52.624 (Google Home) Calling message handler 'onHeartbeat'.
2019-03-25 21:30:00.158 (Google Home) Pushing 'onNotificationCallback' on to queue
2019-03-25 21:30:00.158 Notification sent (Google_Devices) => Success
2019-03-25 21:30:00.169 (Schakelaars) Light/Switch (Test Knop)
2019-03-25 21:30:00.187 (Google Home) Processing 'onNotificationCallback' message
2019-03-25 21:30:00.188 (Google Home) Calling message handler 'onNotification'.
2019-03-25 21:30:00.188 (Google Home) onNotification: Test Knop,Test knop,Test knop,On,0,,/home/pi/domoticz/www/images/Generic48_On.png
2019-03-25 21:30:00.189 (Google Home) handleMessage: 'Test knop', sent to 'Google Huiskamer'
2019-03-25 21:30:00.494 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:00.502 (Google Home) [Google Home - Google Home Volume] Update 2(2):'69'(50): 0(0)
2019-03-25 21:30:00.502 (Google Home - Google Home Volume) Updating device from 2:'50' to have values 2:'69'.
2019-03-25 21:30:00.995 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:00.155 Status: User: Xenomes initiated a switch command (131/Test Knop/On)
2019-03-25 21:30:00.158 Status: Notification: Test knop
2019-03-25 21:30:01.496 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:01.996 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:02.409 Notification sent (email) => Success
2019-03-25 21:30:02.496 (Google Home) [Google Home - Google Home Volume] Update 0(2):'69'(69): 0(0)
2019-03-25 21:30:02.496 (Google Home - Google Home Volume) Updating device from 2:'69' to have values 0:'69'.
2019-03-25 21:30:02.583 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-03-25 21:30:02.593 (Google Home) Processing 'onHeartbeatCallback' message
2019-03-25 21:30:14.317 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:14.324 (Google Home) [Google Home - Google Home Status] Update 9(9):'Screensaver'(Screensaver): 1(0)
2019-03-25 21:30:14.325 (Google Home - Google Home Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-03-25 21:30:14.324 Status: (Google Home) Google Huiskamer is now: LOST
2019-03-25 21:30:15.326 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:15.827 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:16.328 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:16.828 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:17.329 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:17.830 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:18.331 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:18.832 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:19.332 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:20.334 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:20.835 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:21.336 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:21.836 (Google Home) Waiting for 'Default Media Receiver' to start
2019-03-25 21:30:22.355 (Google Home) [Google Home - Google Home Volume] Update 0(0):'50'(69): 0(0)
2019-03-25 21:30:22.356 (Google Home - Google Home Volume) Updating device from 0:'69' to have values 0:'50'.
2019-03-25 21:30:22.389 (Google Home) [Google Home - Google Home Volume] Update 2(0):'50'(50): 0(0)
2019-03-25 21:30:22.389 (Google Home - Google Home Volume) Updating device from 0:'50' to have values 2:'50'.
2019-03-25 21:30:22.341 Error: (Google Home) Notification 'Test knop', sent to 'Google Huiskamer' timed out
2019-03-25 21:30:23.891 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-03-25 21:30:23.910 (Google Home) Processing 'onHeartbeatCallback' message
2019-03-25 21:30:23.911 (Google Home) Calling message handler 'onHeartbeat'.
2019-03-25 21:30:33.893 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-03-25 21:30:33.927 (Google Home) Processing 'onHeartbeatCallback' message
2019-03-25 21:30:33.928 (Google Home) Calling message handler 'onHeartbeat'.

**Comment by dnpwwo** [comment]
Key line for me in this log is:

2019-03-25 21:30:14.324 Status: (Google Home) Google Huiskamer is now: LOST

which means that the library the plugin uses can't communicate with the home device at that exact point in time.  You can't play audio on a device you can't talk to.

Does this always happen or was it a once off? You should see it trying to re-establish communication 5-10 seconds after this message.  Was it successful?

**Comment by Xenomes** [comment]
The error message is always the same, when sending a notification. I am not seeing a retry in the log. The Google home make two sound b.t.w. one soft beep for volume change and a longer sound beep/string when you expect the notification being played. Other function on the Google home works normal.

**Comment by dnpwwo** [comment]
I've pushed a new version tonight that changes the media type and how the plugin waits. Might help.

**Comment by Xenomes** [comment]
Sorry had no time to test the last days.
The error message is gone. The mp3 file is not played, but there is a extra beep for the volume back to original.

**Comment by dnpwwo** [comment]
Can you try the latest version and close the issue if it is now resolved?

**Comment by Xenomes** [comment]
I have follow the other Notification issue, there is sometimes the message in the log. 
`2019-04-13 07:46:41.987 Error: (Google Home) Notification sent to 'Google Huiskamer' timed out
2019-04-13 08:02:00.061 (Google Home) Notification sent to 'Google Huiskamer' completed`

I have updated pychromecast to 3.20, installed gtts and update your script.
But the mp3 file is not being played.
`2019-04-13 08:03:41.121 (Google Home - Chromecast Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.123 (Google Home) [Google Home - Chromecast Source] Update 0(0):'0'(0): 1(0)
2019-04-13 08:03:41.123 (Google Home - Chromecast Source) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.126 (Google Home) [Google Home - Google Huiskamer Status] Update 9(9):'Screensaver'(Screensaver): 1(0)
2019-04-13 08:03:41.127 (Google Home - Google Huiskamer Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.129 (Google Home) [Google Home - Google Huiskamer Volume] Update 2(2):'89'(89): 1(0)
2019-04-13 08:03:41.129 (Google Home - Google Huiskamer Volume) Updating device from 2:'89' to have values 2:'89'.
2019-04-13 08:03:41.132 (Google Home) [Google Home - Google Huiskamer Playing] Update 0(0):'0'(0): 1(0)
2019-04-13 08:03:41.133 (Google Home - Google Huiskamer Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.135 (Google Home) Pushing 'NotifierDirective' on to queue
2019-04-13 08:03:41.144 (Google Home) Pushing 'ProtocolDirective' on to queue
2019-04-13 08:03:41.145 (Google Home) Pushing 'ListenDirective' on to queue
2019-04-13 08:03:41.146 (Google Home) Entering notification handler
2019-04-13 08:03:41.150 (Google Home) Processing 'NotifierDirective' message
2019-04-13 08:03:41.150 (Google Home) Notifier Name set to: Google_Devices.
2019-04-13 08:03:41.151 (Google Home) Processing 'ProtocolDirective' message
2019-04-13 08:03:41.151 (Google Home) Protocol set to: 'HTTP'.
2019-04-13 08:03:41.151 (Google Home) Processing 'ListenDirective' message
2019-04-13 08:03:41.151 (Google Home) Transport set to: 'TCP/IP', :8009.
2019-04-13 08:03:41.152 (Google Home) Listen directive received, action initiated successfully.
2019-04-13 08:03:41.330 (Google Home) Discovery message seen from unknown device, added: 'Chromecast', Model: 'Chromecast', UUID: '6e4e9efa-a724-ab62-3aa4-3cb301a4094f' + IP: '192.168.1.31:8009'
2019-04-13 08:03:41.751 (Google Home) Pushing 'onNotificationCallback' on to queue
2019-04-13 08:03:41.751 Notification sent (Google_Devices) => Success
2019-04-13 08:03:41.752 (Google Home) Processing 'onNotificationCallback' message
2019-04-13 08:03:41.756 (Google Home) Calling message handler 'onNotification'.
2019-04-13 08:03:41.757 (Google Home) onNotification: Test Knop,Dit is een test bericht!,Dit is een test bericht!,On,0,,/home/pi/domoticz/www/images/Generic48_On.png
2019-04-13 08:03:41.757 (Schakelaars) Light/Switch (Test Knop)
2019-04-13 08:03:41.758 (Google Home) handleMessage: 'Dit is een test bericht!', to be sent to 'Google Huiskamer'
2019-04-13 08:03:41.765 (Google Home) [Chromecast Status] Update 9(9):'Screensaver'(Screensaver): 0(1)
2019-04-13 08:03:41.765 (Chromecast Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.774 (Google Home) [Chromecast Status] Update 9(9):'Screensaver'(Screensaver): 1(0)
2019-04-13 08:03:41.774 (Chromecast Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.784 (Google Home) [Google Home - Chromecast Volume] Update 0(0):'100'(100): 0(1)
2019-04-13 08:03:41.784 (Google Home - Chromecast Volume) Updating device from 0:'100' to have values 0:'100'.
2019-04-13 08:03:41.788 (Google Home) [Google Home - Chromecast Playing] Update 0(0):'0'(0): 0(1)
2019-04-13 08:03:41.788 (Google Home - Chromecast Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.791 (Google Home) [Google Home - Chromecast Source] Update 0(0):'0'(0): 0(1)
2019-04-13 08:03:41.791 (Google Home - Chromecast Source) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.828 (Google Home) Discovery message seen from unknown device, added: 'Google Huiskamer', Model: 'Google Home Mini', UUID: '2ea44c50-13d4-0518-bd03-12eabb5b6cc6' + IP: '192.168.1.30:8009'
2019-04-13 08:03:41.829 (Google Home) [Google Home - Google Huiskamer Status] Update 9(9):'Screensaver'(Screensaver): 0(1)
2019-04-13 08:03:41.829 (Google Home - Google Huiskamer Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.832 (Google Home) [Google Home - Google Huiskamer Volume] Update 2(2):'89'(89): 0(1)
2019-04-13 08:03:41.832 (Google Home - Google Huiskamer Volume) Updating device from 2:'89' to have values 2:'89'.
2019-04-13 08:03:41.836 (Google Home) [Google Home - Google Huiskamer Playing] Update 0(0):'0'(0): 0(1)
2019-04-13 08:03:41.836 (Google Home - Google Huiskamer Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.840 (Google Home) [Google Home - Google Huiskamer Status] Update 9(9):'Screensaver'(Screensaver): 1(0)
2019-04-13 08:03:41.840 (Google Home - Google Huiskamer Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.845 (Google Home) [Google Home - Google Huiskamer Volume] Update 2(2):'89'(89): 1(0)
2019-04-13 08:03:41.845 (Google Home - Google Huiskamer Volume) Updating device from 2:'89' to have values 2:'89'.
2019-04-13 08:03:41.848 (Google Home) [Google Home - Google Huiskamer Playing] Update 0(0):'0'(0): 1(0)
2019-04-13 08:03:41.848 (Google Home - Google Huiskamer Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.853 (Google Home) [Google Home - Chromecast Volume] Update 0(0):'100'(100): 1(0)
2019-04-13 08:03:41.853 (Google Home - Chromecast Volume) Updating device from 0:'100' to have values 0:'100'.
2019-04-13 08:03:41.857 (Google Home) [Google Home - Chromecast Playing] Update 0(0):'0'(0): 1(0)
2019-04-13 08:03:41.857 (Google Home - Chromecast Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.876 (Google Home) [Google Home - Chromecast Source] Update 0(0):'0'(0): 1(0)
2019-04-13 08:03:41.876 (Google Home - Chromecast Source) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.928 (Google Home) [Chromecast Status] Update 9(9):'Screensaver'(Screensaver): 0(1)
2019-04-13 08:03:41.928 (Chromecast Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.935 (Google Home) [Google Home - Chromecast Volume] Update 0(0):'100'(100): 0(1)
2019-04-13 08:03:41.935 (Google Home - Chromecast Volume) Updating device from 0:'100' to have values 0:'100'.
2019-04-13 08:03:41.939 (Google Home) [Google Home - Chromecast Playing] Update 0(0):'0'(0): 0(1)
2019-04-13 08:03:41.939 (Google Home - Chromecast Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.944 (Google Home) [Google Home - Chromecast Source] Update 0(0):'0'(0): 0(1)
2019-04-13 08:03:41.944 (Google Home - Chromecast Source) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.978 (Google Home) [Google Home - Google Huiskamer Status] Update 9(9):'Screensaver'(Screensaver): 0(1)
2019-04-13 08:03:41.978 (Google Home - Google Huiskamer Status) Updating device from 9:'Screensaver' to have values 9:'Screensaver'.
2019-04-13 08:03:41.984 (Google Home) [Google Home - Google Huiskamer Volume] Update 2(2):'89'(89): 0(1)
2019-04-13 08:03:41.984 (Google Home - Google Huiskamer Volume) Updating device from 2:'89' to have values 2:'89'.
2019-04-13 08:03:41.989 (Google Home) [Google Home - Google Huiskamer Playing] Update 0(0):'0'(0): 0(1)
2019-04-13 08:03:41.989 (Google Home - Google Huiskamer Playing) Updating device from 0:'0' to have values 0:'0'.
2019-04-13 08:03:41.096 Status: (Google Home) Entering work loop.
2019-04-13 08:03:41.097 Status: (Google Home) Initialized version 1.15.3, author 'dnpwwo'
2019-04-13 08:03:41.728 Status: User: Xenomes initiated a switch command (131/Test Knop/On)
2019-04-13 08:03:41.751 Status: Notification: Dit is een test bericht!
2019-04-13 08:03:41.773 Status: (Google Home) Chromecast is now: CONNECTING
2019-04-13 08:03:41.840 Status: (Google Home) Google Huiskamer is now: CONNECTING
2019-04-13 08:03:41.853 Status: (Google Home) Chromecast is now: CONNECTED
2019-04-13 08:03:41.921 Status: (Google Home) Google Huiskamer is now: CONNECTED
2019-04-13 08:03:42.973 (Google Home) [Google Home - Google Huiskamer Volume] Update 2(2):'69'(89): 0(0)
2019-04-13 08:03:42.973 (Google Home - Google Huiskamer Volume) Updating device from 2:'89' to have values 2:'69'.
2019-04-13 08:03:44.906 (Google Home) [Google Home - Google Huiskamer Volume] Update 0(2):'69'(69): 0(0)
2019-04-13 08:03:44.906 (Google Home - Google Huiskamer Volume) Updating device from 2:'69' to have values 0:'69'.
2019-04-13 08:03:45.906 (Google Home) Waiting for player (timeout in 69.9997673034668 seconds)
2019-04-13 08:03:46.407 (Google Home) Waiting for player (timeout in 69.49888157844543 seconds)
2019-04-13 08:03:46.917 (Google Home) Waiting for player (timeout in 68.98898148536682 seconds)
2019-04-13 08:03:47.418 (Google Home) Waiting for player (timeout in 68.48806834220886 seconds)
2019-04-13 08:03:47.919 (Google Home) Waiting for player (timeout in 67.98718905448914 seconds)
2019-04-13 08:03:48.420 (Google Home) Waiting for player (timeout in 67.48630928993225 seconds)
2019-04-13 08:03:48.921 (Google Home) Waiting for player (timeout in 66.98542428016663 seconds)
2019-04-13 08:03:49.421 (Google Home) Waiting for player (timeout in 66.484534740448 seconds)
2019-04-13 08:03:49.922 (Google Home) Waiting for player (timeout in 65.98368215560913 seconds)
2019-04-13 08:03:50.423 (Google Home) Waiting for player (timeout in 65.48280835151672 seconds)
2019-04-13 08:03:50.924 (Google Home) Waiting for player (timeout in 64.98194932937622 seconds)
2019-04-13 08:03:51.098 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:03:51.123 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:03:51.123 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:03:51.425 (Google Home) Waiting for player (timeout in 64.48105573654175 seconds)
2019-04-13 08:03:51.934 (Google Home) Waiting for player (timeout in 63.97155547142029 seconds)
2019-04-13 08:03:52.435 (Google Home) Waiting for player (timeout in 63.47067594528198 seconds)
2019-04-13 08:03:52.936 (Google Home) Waiting for player (timeout in 62.96980094909668 seconds)
2019-04-13 08:03:53.437 (Google Home) Waiting for player (timeout in 62.468923568725586 seconds)
2019-04-13 08:03:53.938 (Google Home) Waiting for player (timeout in 61.96806263923645 seconds)
2019-04-13 08:03:54.439 (Google Home) Waiting for player (timeout in 61.46718168258667 seconds)
2019-04-13 08:03:54.940 (Google Home) Waiting for player (timeout in 60.966280698776245 seconds)
2019-04-13 08:03:55.441 (Google Home) Waiting for player (timeout in 60.465388774871826 seconds)
2019-04-13 08:03:55.941 (Google Home) Waiting for player (timeout in 59.964518547058105 seconds)
2019-04-13 08:03:56.442 (Google Home) Waiting for player (timeout in 59.463640451431274 seconds)
2019-04-13 08:03:57.818 (Google Home) Waiting for player (timeout in 58.08797335624695 seconds)
2019-04-13 08:03:58.319 (Google Home) Waiting for player (timeout in 57.58709740638733 seconds)
2019-04-13 08:03:58.820 (Google Home) Waiting for player (timeout in 57.08620858192444 seconds)
2019-04-13 08:03:59.321 (Google Home) Waiting for player (timeout in 56.58525729179382 seconds)
2019-04-13 08:03:59.822 (Google Home) Waiting for player (timeout in 56.08438587188721 seconds)
2019-04-13 08:04:00.322 (Google Home) Waiting for player (timeout in 55.58377456665039 seconds)
2019-04-13 08:04:00.823 (Google Home) Waiting for player (timeout in 55.082897424697876 seconds)
2019-04-13 08:04:01.100 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:04:01.105 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:04:01.105 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:04:02.331 (Google Home) Waiting for player (timeout in 53.57463765144348 seconds)
2019-04-13 08:04:02.832 (Google Home) Waiting for player (timeout in 53.073760747909546 seconds)
2019-04-13 08:04:03.333 (Google Home) Waiting for player (timeout in 52.57288074493408 seconds)
2019-04-13 08:04:03.834 (Google Home) Waiting for player (timeout in 52.07201147079468 seconds)
2019-04-13 08:04:04.335 (Google Home) Waiting for player (timeout in 51.571130990982056 seconds)
2019-04-13 08:04:04.836 (Google Home) Waiting for player (timeout in 51.07023787498474 seconds)
2019-04-13 08:04:05.337 (Google Home) Waiting for player (timeout in 50.56928372383118 seconds)
2019-04-13 08:04:05.838 (Google Home) Waiting for player (timeout in 50.06834435462952 seconds)
2019-04-13 08:04:06.338 (Google Home) Waiting for player (timeout in 49.56746578216553 seconds)
2019-04-13 08:04:07.347 (Google Home) Waiting for player (timeout in 48.559006452560425 seconds)
2019-04-13 08:04:07.849 (Google Home) Waiting for player (timeout in 48.05749320983887 seconds)
2019-04-13 08:04:08.349 (Google Home) Waiting for player (timeout in 47.556583642959595 seconds)
2019-04-13 08:04:08.851 (Google Home) Waiting for player (timeout in 47.054713010787964 seconds)
2019-04-13 08:04:09.352 (Google Home) Waiting for player (timeout in 46.55376982688904 seconds)
2019-04-13 08:04:09.853 (Google Home) Waiting for player (timeout in 46.05276346206665 seconds)
2019-04-13 08:04:10.354 (Google Home) Waiting for player (timeout in 45.55179762840271 seconds)
2019-04-13 08:04:10.855 (Google Home) Waiting for player (timeout in 45.050918102264404 seconds)
2019-04-13 08:04:11.102 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:04:11.133 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:04:11.133 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:04:11.356 (Google Home) Waiting for player (timeout in 44.55015468597412 seconds)
2019-04-13 08:04:12.358 (Google Home) Waiting for player (timeout in 43.548402547836304 seconds)
2019-04-13 08:04:12.858 (Google Home) Waiting for player (timeout in 43.04751467704773 seconds)
2019-04-13 08:04:13.359 (Google Home) Waiting for player (timeout in 42.546592235565186 seconds)
2019-04-13 08:04:13.860 (Google Home) Waiting for player (timeout in 42.045655250549316 seconds)
2019-04-13 08:04:14.361 (Google Home) Waiting for player (timeout in 41.54475164413452 seconds)
2019-04-13 08:04:14.862 (Google Home) Waiting for player (timeout in 41.043853521347046 seconds)
2019-04-13 08:04:15.363 (Google Home) Waiting for player (timeout in 40.54296064376831 seconds)
2019-04-13 08:04:15.864 (Google Home) Waiting for player (timeout in 40.04199743270874 seconds)
2019-04-13 08:04:16.365 (Google Home) Waiting for player (timeout in 39.54121780395508 seconds)
2019-04-13 08:04:17.367 (Google Home) Waiting for player (timeout in 38.53949189186096 seconds)
2019-04-13 08:04:17.868 (Google Home) Waiting for player (timeout in 38.038373708724976 seconds)
2019-04-13 08:04:18.369 (Google Home) Waiting for player (timeout in 37.537469148635864 seconds)
2019-04-13 08:04:18.869 (Google Home) Waiting for player (timeout in 37.036529541015625 seconds)
2019-04-13 08:04:19.370 (Google Home) Waiting for player (timeout in 36.53565955162048 seconds)
2019-04-13 08:04:19.871 (Google Home) Waiting for player (timeout in 36.03477144241333 seconds)
2019-04-13 08:04:20.372 (Google Home) Waiting for player (timeout in 35.53386831283569 seconds)
2019-04-13 08:04:20.873 (Google Home) Waiting for player (timeout in 35.032975912094116 seconds)
2019-04-13 08:04:21.104 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:04:21.150 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:04:21.150 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:04:21.374 (Google Home) Waiting for player (timeout in 34.532087564468384 seconds)
2019-04-13 08:04:22.376 (Google Home) Waiting for player (timeout in 33.53030014038086 seconds)
2019-04-13 08:04:22.877 (Google Home) Waiting for player (timeout in 33.02940249443054 seconds)
2019-04-13 08:04:23.378 (Google Home) Waiting for player (timeout in 32.5284469127655 seconds)
2019-04-13 08:04:23.976 (Google Home) Waiting for player (timeout in 31.930195569992065 seconds)
2019-04-13 08:04:24.477 (Google Home) Waiting for player (timeout in 31.429173707962036 seconds)
2019-04-13 08:04:24.978 (Google Home) Waiting for player (timeout in 30.928288221359253 seconds)
2019-04-13 08:04:25.479 (Google Home) Waiting for player (timeout in 30.427397966384888 seconds)
2019-04-13 08:04:25.980 (Google Home) Waiting for player (timeout in 29.926443815231323 seconds)
2019-04-13 08:04:26.480 (Google Home) Waiting for player (timeout in 29.425689458847046 seconds)
2019-04-13 08:04:27.482 (Google Home) Waiting for player (timeout in 28.423990726470947 seconds)
2019-04-13 08:04:27.983 (Google Home) Waiting for player (timeout in 27.923114776611328 seconds)
2019-04-13 08:04:28.484 (Google Home) Waiting for player (timeout in 27.422168016433716 seconds)
2019-04-13 08:04:31.105 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:04:31.133 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:04:31.133 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:04:31.580 (Google Home) Waiting for player (timeout in 24.325873136520386 seconds)
2019-04-13 08:04:32.081 (Google Home) Waiting for player (timeout in 23.82495641708374 seconds)
2019-04-13 08:04:32.582 (Google Home) Waiting for player (timeout in 23.324036836624146 seconds)
2019-04-13 08:04:33.083 (Google Home) Waiting for player (timeout in 22.823137283325195 seconds)
2019-04-13 08:04:33.584 (Google Home) Waiting for player (timeout in 22.32208013534546 seconds)
2019-04-13 08:04:34.085 (Google Home) Waiting for player (timeout in 21.821136951446533 seconds)
2019-04-13 08:04:34.586 (Google Home) Waiting for player (timeout in 21.320329666137695 seconds)
2019-04-13 08:04:35.087 (Google Home) Waiting for player (timeout in 20.819429636001587 seconds)
2019-04-13 08:04:35.587 (Google Home) Waiting for player (timeout in 20.318530559539795 seconds)
2019-04-13 08:04:36.088 (Google Home) Waiting for player (timeout in 19.81763768196106 seconds)
2019-04-13 08:04:36.589 (Google Home) Waiting for player (timeout in 19.316875219345093 seconds)
2019-04-13 08:04:37.090 (Google Home) Waiting for player (timeout in 18.816088676452637 seconds)
2019-04-13 08:04:37.591 (Google Home) Waiting for player (timeout in 18.31517767906189 seconds)
2019-04-13 08:04:38.092 (Google Home) Waiting for player (timeout in 17.81429672241211 seconds)
2019-04-13 08:04:38.593 (Google Home) Waiting for player (timeout in 17.313402891159058 seconds)
2019-04-13 08:04:39.094 (Google Home) Waiting for player (timeout in 16.812471389770508 seconds)
2019-04-13 08:04:39.602 (Google Home) Waiting for player (timeout in 16.303926706314087 seconds)
2019-04-13 08:04:40.103 (Google Home) Waiting for player (timeout in 15.803013563156128 seconds)
2019-04-13 08:04:40.604 (Google Home) Waiting for player (timeout in 15.301971435546875 seconds)
2019-04-13 08:04:41.105 (Google Home) Waiting for player (timeout in 14.80082392692566 seconds)
2019-04-13 08:04:41.107 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:04:41.157 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:04:41.157 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:04:41.606 (Google Home) Waiting for player (timeout in 14.299830675125122 seconds)
2019-04-13 08:04:42.107 (Google Home) Waiting for player (timeout in 13.798976421356201 seconds)
2019-04-13 08:04:42.608 (Google Home) Waiting for player (timeout in 13.2981595993042 seconds)
2019-04-13 08:04:43.109 (Google Home) Waiting for player (timeout in 12.797345161437988 seconds)
2019-04-13 08:04:43.609 (Google Home) Waiting for player (timeout in 12.296555280685425 seconds)
2019-04-13 08:04:44.110 (Google Home) Waiting for player (timeout in 11.795661926269531 seconds)
2019-04-13 08:04:44.611 (Google Home) Waiting for player (timeout in 11.294893741607666 seconds)
2019-04-13 08:04:45.112 (Google Home) Waiting for player (timeout in 10.79410457611084 seconds)
2019-04-13 08:04:45.613 (Google Home) Waiting for player (timeout in 10.293062448501587 seconds)
2019-04-13 08:04:46.114 (Google Home) Waiting for player (timeout in 9.792207956314087 seconds)
2019-04-13 08:04:46.615 (Google Home) Waiting for player (timeout in 9.29145359992981 seconds)
2019-04-13 08:04:47.115 (Google Home) Waiting for player (timeout in 8.790671586990356 seconds)
2019-04-13 08:04:47.616 (Google Home) Waiting for player (timeout in 8.289782285690308 seconds)
2019-04-13 08:04:48.117 (Google Home) Waiting for player (timeout in 7.7888524532318115 seconds)
2019-04-13 08:04:48.618 (Google Home) Waiting for player (timeout in 7.287960529327393 seconds)
2019-04-13 08:04:49.119 (Google Home) Waiting for player (timeout in 6.787058115005493 seconds)
2019-04-13 08:04:49.620 (Google Home) Waiting for player (timeout in 6.286156415939331 seconds)
2019-04-13 08:04:50.127 (Google Home) Waiting for player (timeout in 5.77891993522644 seconds)
2019-04-13 08:04:50.628 (Google Home) Waiting for player (timeout in 5.277966737747192 seconds)
2019-04-13 08:04:51.109 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:04:51.125 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:04:51.125 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:04:51.129 (Google Home) Waiting for player (timeout in 4.777065277099609 seconds)
2019-04-13 08:04:51.630 (Google Home) Waiting for player (timeout in 4.2762672901153564 seconds)
2019-04-13 08:04:52.131 (Google Home) Waiting for player (timeout in 3.775388479232788 seconds)
2019-04-13 08:04:52.632 (Google Home) Waiting for player (timeout in 3.2745280265808105 seconds)
2019-04-13 08:04:53.132 (Google Home) Waiting for player (timeout in 2.7735848426818848 seconds)
2019-04-13 08:04:53.633 (Google Home) Waiting for player (timeout in 2.272630214691162 seconds)
2019-04-13 08:04:54.134 (Google Home) Waiting for player (timeout in 1.7717220783233643 seconds)
2019-04-13 08:04:54.635 (Google Home) Waiting for player (timeout in 1.2707788944244385 seconds)
2019-04-13 08:04:55.136 (Google Home) Waiting for player (timeout in 0.7698209285736084 seconds)
2019-04-13 08:04:55.637 (Google Home) Waiting for player (timeout in 0.26884937286376953 seconds)
2019-04-13 08:04:55.858 (Slimme meter) Usage (Delivery L1)
2019-04-13 08:04:56.148 (Google Home) [Google Home - Google Huiskamer Volume] Update 0(0):'89'(69): 0(0)
2019-04-13 08:04:56.148 (Google Home - Google Huiskamer Volume) Updating device from 0:'69' to have values 0:'89'.
2019-04-13 08:04:56.179 (Google Home) [Google Home - Google Huiskamer Volume] Update 2(0):'89'(89): 0(0)
2019-04-13 08:04:56.179 (Google Home - Google Huiskamer Volume) Updating device from 0:'89' to have values 2:'89'.
2019-04-13 08:04:56.140 Error: (Google Home) Notification sent to 'Google Huiskamer' timed out
2019-04-13 08:05:01.112 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:05:01.657 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:05:01.657 (Google Home) Calling message handler 'onHeartbeat'.
2019-04-13 08:05:11.659 (Google Home) Pushing 'onHeartbeatCallback' on to queue
2019-04-13 08:05:11.676 (Google Home) Processing 'onHeartbeatCallback' message
2019-04-13 08:05:11.676 (Google Home) Calling message handler 'onHeartbeat'.
`

**Comment by jeroenkl** [comment]
I've got the same issue. Update to latest version didn't fix it
	1.16.13 - Bugfix: Handle groups changing 'elected leader'

best regards, Jeroen

**Comment by dnpwwo** [comment]
I assume you have you Domoticz set to use Dutch so I set my test system to match and the test message played in Dutch.  With the logging level set to 'Python Only' I got:

> 2019-04-14 17:31:25.339  (Google Devices) onCommand called for Unit 2: Parameter 'SendNotification Dit is een test bericht', Level: 0
2019-04-14 17:31:25.340  (Google Devices) UUID: 9c72b737-74fb-8e34-5ceb-10ba04302cc2, sub unit: -1, Action: Sendnotification, params: Dit is een test bericht
2019-04-14 17:31:25.340  (Google Devices) handleMessage: 'Dit is een test bericht', to be sent to 'Lounge Speaker'
2019-04-14 17:31:27.886  (Google Devices) [Lounge Home - Volume] Update 2(2):'40'(37): 0(0)
2019-04-14 17:31:28.034  (Google Devices) [Lounge Home - Volume] Update 0(2):'40'(40): 0(0)
**2019-04-14 17:31:28.212  (Google Devices) xxx.xxx.xxx.xxx:40506 Connection established
2019-04-14 17:31:28.213  (Google Devices) xxx.xxx.xxx.xxx:40506 Sent 'GET' request file '/message.mp3' from position 0**
2019-04-14 17:31:28.345  (Google Devices) [Lounge Home - Volume] Update 2(0):'40'(40): 0(0)
2019-04-14 17:31:28.351  (Google Devices) [Lounge Home - Playing] Update 2(0):'1'(0): 0(0)
**2019-04-14 17:31:28.516  (Google Devices) xxx.xxx.xxx.xxx:40506 Connection disconnected**
2019-04-14 17:31:28.880  (Google Devices) Waiting for message to complete playing (timeout in 69.9 seconds)
2019-04-14 17:31:29.381  (Google Devices) Waiting for message to complete playing (timeout in 69.4 seconds)
2019-04-14 17:31:29.882  (Google Devices) Waiting for message to complete playing (timeout in 68.9 seconds)
2019-04-14 17:31:30.383  (Google Devices) Waiting for message to complete playing (timeout in 68.4 seconds)
2019-04-14 17:31:30.823  (Google Devices) [All Speakers - Volume] Update 2(2):'44'(43): 0(0)
2019-04-14 17:31:30.830  Status: LUA: Device based event fired on 'All Speakers - Volume', value 'Set Level: 44 %'
2019-04-14 17:31:30.842  (Google Devices) [Google Devices - Downstairs Speakers Volume] Update 2(2):'45'(44): 0(0)
2019-04-14 17:31:30.884  (Google Devices) Waiting for message to complete playing (timeout in 67.9 seconds)
2019-04-14 17:31:31.385  (Google Devices) Waiting for message to complete playing (timeout in 67.4 seconds)
2019-04-14 17:31:31.864  (Google Devices) [Lounge Home - Playing] Update 2(2):'44'(1): 0(0)
2019-04-14 17:31:31.886  (Google Devices) Waiting for message to complete playing (timeout in 66.9 seconds)
2019-04-14 17:31:32.387  (Google Devices) Waiting for message to complete playing (timeout in 66.4 seconds)
2019-04-14 17:31:32.888  (Google Devices) Waiting for message to complete playing (timeout in 65.9 seconds)
2019-04-14 17:31:32.953  (Google Devices) [Lounge Home - Volume] Update 0(2):'40'(40): 0(0)
2019-04-14 17:31:32.959  (Google Devices) [Lounge Home - Playing] Update 0(2):'0'(44): 0(0)
2019-04-14 17:31:33.390  (Google Devices) Notification sent to 'Lounge Speaker' completed

What it shows is that for you the Google Home never came back to ask for the file.  For me it did (lines in bold show the file being served).  Either you have a firewall blocking it or you just tested too early.

Try starting Domoticz, waiting until all the devices aren't 'red' anymore and then retest.

**Comment by jeroenkl** [comment]
Hi dnpwwo,

Yes, Domoticz in Dutch, latest beta running.

Log:
2019-04-14 15:18:20.664 Notification sent (Google_Devices) => Success
2019-04-14 15:18:20.705 (Google Home) onNotification: Ikea - Lamp stoel,Lamp stoel is aangegaan,Lamp stoel is aangegaan,On,0,,/home/pi/domoticz/www/images/Uplighter48_On.png
2019-04-14 15:18:20.706 (Google Home) handleMessage: 'Lamp stoel is aangegaan', to be sent to 'Huiskamer'
2019-04-14 15:18:22.255 (Google Home) [Google Home - Huiskamer Volume] Update 2(2):'50'(40): 0(0)
2019-04-14 15:18:22.287 (Google Home) [Google Home - Thuisgroep Volume] Update 2(2):'50'(40): 0(0)
2019-04-14 15:18:22.498 (Google Home) [Google Home - Huiskamer Volume] Update 0(2):'50'(50): 0(0)
2019-04-14 15:18:23.533 (Google Home) Waiting for player (timeout in 69.99989581108093 seconds)
2019-04-14 15:18:24.034 (Google Home) Waiting for player (timeout in 69.49892044067383 seconds)
2019-04-14 15:18:24.535 (Google Home) Waiting for player (timeout in 68.99799799919128 seconds)
2019-04-14 15:18:25.036 (Google Home) Waiting for player (timeout in 68.49691390991211 seconds)
2019-04-14 15:18:25.537 (Google Home) Waiting for player (timeout in 67.99588465690613 seconds)
2019-04-14 15:18:26.038 (Google Home) Waiting for player (timeout in 67.49488091468811 seconds)
2019-04-14 15:18:26.539 (Google Home) Waiting for player (timeout in 66.99395608901978 seconds)
2019-04-14 15:18:27.040 (Google Home) Waiting for player (timeout in 66.49302196502686 seconds)
2019-04-14 15:18:27.541 (Google Home) Waiting for player (timeout in 65.99213886260986 seconds)
2019-04-14 15:18:28.042 (Google Home) Waiting for player (timeout in 65.4912486076355 seconds)
2019-04-14 15:18:29.044 (Google Home) Waiting for player (timeout in 64.48930215835571 seconds)
2019-04-14 15:18:29.545 (Google Home) Waiting for player (timeout in 63.98833131790161 seconds)
2019-04-14 15:18:30.046 (Google Home) Waiting for player (timeout in 63.4874382019043 seconds)
2019-04-14 15:18:30.547 (Google Home) Waiting for player (timeout in 62.98652768135071 seconds)
2019-04-14 15:18:31.048 (Google Home) Waiting for player (timeout in 62.485663175582886 seconds)
2019-04-14 15:18:31.548 (Google Home) Waiting for player (timeout in 61.98474621772766 seconds)
2019-04-14 15:18:32.049 (Google Home) Waiting for player (timeout in 61.48383975028992 seconds)
2019-04-14 15:18:32.550 (Google Home) Waiting for player (timeout in 60.982913970947266 seconds)
2019-04-14 15:18:33.051 (Google Home) Waiting for player (timeout in 60.48203730583191 seconds)
2019-04-14 15:18:34.053 (Google Home) Waiting for player (timeout in 59.480212926864624 seconds)
2019-04-14 15:18:34.554 (Google Home) Waiting for player (timeout in 58.97927236557007 seconds)
2019-04-14 15:18:35.055 (Google Home) Waiting for player (timeout in 58.47830605506897 seconds)
2019-04-14 15:18:35.556 (Google Home) Waiting for player (timeout in 57.9774067401886 seconds)
2019-04-14 15:18:36.057 (Google Home) Waiting for player (timeout in 57.47651195526123 seconds)
2019-04-14 15:18:36.558 (Google Home) Waiting for player (timeout in 56.975521087646484 seconds)
2019-04-14 15:18:37.059 (Google Home) Waiting for player (timeout in 56.47457432746887 seconds)
2019-04-14 15:18:37.559 (Google Home) Waiting for player (timeout in 55.97368264198303 seconds)
2019-04-14 15:18:38.060 (Google Home) Waiting for player (timeout in 55.47280430793762 seconds)
2019-04-14 15:18:39.062 (Google Home) Waiting for player (timeout in 54.4713659286499 seconds)
2019-04-14 15:18:39.563 (Google Home) Waiting for player (timeout in 53.97049689292908 seconds)
2019-04-14 15:18:40.063 (Google Home) Waiting for player (timeout in 53.46965146064758 seconds)
2019-04-14 15:18:40.564 (Google Home) Waiting for player (timeout in 52.96876239776611 seconds)
2019-04-14 15:18:41.065 (Google Home) Waiting for player (timeout in 52.46785068511963 seconds)
2019-04-14 15:18:41.566 (Google Home) Waiting for player (timeout in 51.96695685386658 seconds)
2019-04-14 15:18:42.067 (Google Home) Waiting for player (timeout in 51.4661009311676 seconds)
2019-04-14 15:18:42.568 (Google Home) Waiting for player (timeout in 50.96522331237793 seconds)
2019-04-14 15:18:43.069 (Google Home) Waiting for player (timeout in 50.46435022354126 seconds
xxxx
xxxx
2019-04-14 15:19:31.659 (Google Home) Waiting for player (timeout in 1.8742473125457764 seconds)
2019-04-14 15:19:32.160 (Google Home) Waiting for player (timeout in 1.373375415802002 seconds)
2019-04-14 15:19:32.661 (Google Home) Waiting for player (timeout in 0.8724842071533203 seconds)
2019-04-14 15:19:33.162 (Google Home) Waiting for player (timeout in 0.371610164642334 seconds)
2019-04-14 15:19:33.677 (Google Home) [Google Home - Huiskamer Volume] Update 0(0):'40'(50): 0(0)
2019-04-14 15:19:33.717 (Google Home) [Google Home - Thuisgroep Volume] Update 2(2):'40'(50): 0(0)
2019-04-14 15:19:33.758 (Google Home) [Google Home - Huiskamer Volume] Update 2(0):'40'(40): 0(0)
2019-04-14 15:19:33.669 Error: (Google Home) Notification sent to 'Huiskamer' timed out

No firewall in between, domoticz is rebooted.

**Comment by Xenomes** [comment]
My Domoticz is in Dutch and the latest beta version running. No Firewall between the two devices, Chrome streaming is working. I have now a Chromecast connected, i got the same messages. but is can see that the player is waiting to receive the file and closed when the timeout is over.
[Log 19-04-2019.txt](https://github.com/dnpwwo/Domoticz-Google-Plugin/files/3097205/Log.19-04-2019.txt)
